# Generated by Django 2.1.4 on 2018-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('rating', models.FloatField()),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
