# Generated by Django 2.1.4 on 2018-12-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181206_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
