# Generated by Django 2.1.4 on 2018-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
